name: Lint
on:
  push:
    branches:
      - "main"
      - "test/**"
      - "release/**"
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "go.*"
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.25.1"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.4.0

      - name: Format code
        run: |
          make format
          git diff --exit-code ||
            (echo "Code is not formatted. Please run 'make format' and commit the changes." && exit 1)

    timeout-minutes: 10
